# Generated by Django 4.1.3 on 2023-04-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='private_key',
            field=models.CharField(default='', max_length=200, verbose_name='private_key'),
            preserve_default=False,
        ),
    ]
